В Kotlin нет проверяемых исключений. Для этого существует целый ряд причин, но мы рассмотрим простой пример, который иллюстрирует причину этого.

Приведённый ниже фрагмент кода является примером простого интерфейса в JDK, который реализован в классе `StringBuilder`.

```java
Appendable append(CharSequence csq) throws IOException;
```

Сигнатура говорит, что каждый раз, когда я присоединяю строку к чему-то (к `StringBuilder`, какому-нибудь логу, сообщению в консоль и т.п), мне необходимо отлавливать исключения типа `IOExceptions`. Почему? Потому, что данная операция может вызывать IO (Input-Output: Ввод-Вывод) (`Writer` также реализует интерфейс `Appendable`). Данный факт постоянно приводит к написанию подобного кода:

```kotlin
try {
    log.append(message)
} catch (IOException e) {
    // Должно быть безопасно
}
```

И это плохо.

Если вы хотите предупредить вызывающие объекты о возможных исключениях при вызове Kotlin кода из Java, вы можете использовать аннотацию `@Throws`.

```kotlin
@Throws(IOException::class) 
fun foo() { 
	throw IOException() 
}
```